### ISSUE TITLE
Add Discord Hooks for the Forum

### ISSUE THREAD

**Issue by ryanford** [TheOdinProject/discussions#10]
In order to ease the burden of checking too many notification sources, it would be nice to have discord hooks for the forum. Definitely would need to be certain tags only to filter out all the check-in spam. Can the bots to this? What do we need to set this up?

*Edit:* to clarify: yes, I'm suggesting/requesting a stream/feed of forum posts in a designated channel. At least titles and a link.

**Comment by mindovermiles262** [comment]
I'm having trouble deciphering what you're asking.  

If you want notifications from the forum why not just sign up for an email newsletter of updates? I think that enabling some kind of feed from Fourm to discord will just clutter discord.

**Comment by ryanford** [comment]
@mindovermiles262 sorry for your troubles. I don't think it would clutter discord. it's easy enough to mute a channel and it's *very* helpful to have all your notifications in one place. This would help us to provide prompt responses to issues on the forum, and take care of them as they come in.

If you're concerned about clutter on discord, maybe we can start a new topic about removing some of the 13 (12 if you take out the live stream discussion) off-topic discussion channels, or the track discussion channels since we're moving those disucssion to gh.

**Comment by codyloyd** [comment]
I don't hate this idea... especially since it's easy enough to mute them.  I like having everything in one place as well, never think to check the forum and would likely just archive any email it sent me.

**Comment by I3uckwheat** [comment]
+1 from me on this

**Comment by codyloyd** [comment]
I DID IT

**Comment by I3uckwheat** [comment]
![image](https://user-images.githubusercontent.com/4411701/80532513-84b88000-8959-11ea-84b4-8330de95739e.png)

**Comment by codyloyd** [comment]
RECURSION
