### ISSUE TITLE
Student Submissions

### ISSUE THREAD

**Issue by mindovermiles262** [TheOdinProject/discussions#13]
Enough is enough.

I think we spend too much time approving student submissions. We need to find a way to automate this.

One idea would be to write a small form. The user goes to a page on TOP (Maybe `theodinproject.com/submit`) where they choose the lesson and provide links to the content. After submission the entries are held in a queue.

Then, once a day, the queue makes one big pr to the curriculum repo. Mods approve and merge the PR.

This frees us from countless daily PRs.

I think it would be quick and easy until we can get the student project submissions up and running.

**Comment by I3uckwheat** [comment]
If we can get students to click the right lesson, I'm on board. 

A query parameter in a link from the project page may be easy to implement.

**Comment by mindovermiles262** [comment]
Talking with @KevinMulhern in Discord:

> Kevin
 3 weeks and I can have the full student submission feature done. I’ve plenty of time with lock down lool. Can you hold off until then?
BriggsE
3 weeks won't be too bad
We've gone this long
Kevin
It would just seem like wasted effort if we put something temporary in right now.
Could be sooner than 3 weeks even.

Lets hold on on this.

**Comment by codyloyd** [comment]
Since Kev is actively working on this feature can we close this discussion for now?

**Comment by I3uckwheat** [comment]
@codyloyd I think we should close it after the standup

**Comment by codyloyd** [comment]
look we did it
