### ISSUE TITLE
Proposal Approval process

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/discussions#18]
We need a defined process for approving proposals as they are submitted. It doesn't have to be _super_ concrete, but IMO our team is too big to rely on just getting an overall vibe in the chatroom and/or unanimous consent.

My only real idea.. and one that I am not particularly attached to: 

A voting process requiring a certain number of yes votes from the moderator team. (should also consider a certain number of _overall_ votes... if only 3 people vote, that's probably not enough to consider a real decision)

**Comment by I3uckwheat** [comment]
I think we could put it up in the chat if we think it needs community input. They can make comments about it and such and we can see what they think there. Using the emojis for 👍 and 👎 would be useful on the PRs for the proposals.

**Comment by codyloyd** [comment]
I think community input is not our best plan.. should stick to mods.

**Comment by I3uckwheat** [comment]
A method where every Core member has to vote yay or nay could work. If we have 2/3, of the vote, we move it forward. Otherwise it's dropped. 

With "retiring" inactive core members, this should be pretty easy to keep in check.

**Comment by codyloyd** [comment]
yeah.. i don't hate this idea, but maybe keep it to like 80-90% of the team or something?  If someone has literally no opinion on something i'd hate for them to feel like they HAVE to weigh in and skew the vote where others might have real opinions.

not sure how likely that is to come up though

**Comment by I3uckwheat** [comment]
@codyloyd I could be down with that. 8/10 have to vote, 2/3 of those have to agree.

Though, it seems like everybody has an opinion no matter what. I would just hate to see people not voting to protest something moving forward. Especially as this gets more formal.

**Comment by codyloyd** [comment]
Yeah definitely.. we can’t just have 3 people voting to make any important decisions

**Comment by I3uckwheat** [comment]
What happens when too many people "don't have opinions"?

**Comment by codyloyd** [comment]
I do not know.  Maybe that would be a reason to table the proposal

**Comment by I3uckwheat** [comment]
I think we need a process to bring it back up then. So it just doesn't sit forever in limbo.

**Comment by codyloyd** [comment]
yeah.. i mean for now it could just be "bug people until we get enough votes" lol

**Comment by I3uckwheat** [comment]
Works for me! lol I've added this to the meeting agenda for tomorrow, so we can talk then too.

**Comment by mindovermiles262** [comment]
Following up on this @I3uckwheat - Did we make any decisions during the stand up?

**Comment by I3uckwheat** [comment]
@mindovermiles262 nothing solid, but we're trying a simple voting system on the pair programming removal

**Comment by codyloyd** [comment]
the thumbsup/down system seems good enough for now.  Closing discussion
