### ISSUE TITLE
Cinco De Mayo Standup

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/discussions#24]
May 5, 2020.  1300UTC

## Follow up on the previous week's agenda
[previous week's notes](https://github.com/TheOdinProject/discussions/blob/master/meeting-notes/2020-04-28.md)
 - Student Submissions Project (Kevin)
 - Lesson Content Proposal (Cody)
 - Roles (Briggs)
 - Rails Course replacement (Austin)

## This week
 - Moving people to maintainer role
 - Remove pair programming from wd101 #27 
 - Live coding #26 
 - Proposal Approval Process #18 
 - Promotion to maintainer onboarding process
 - Move track choice after wd101 #28

**Comment by mindovermiles262** [comment]
I think we can all agree a morning Margarita is an order. We'll discuss who's marg is best.

**Comment by codyloyd** [comment]
![](https://media.giphy.com/media/NH2UmjpiikRtC/giphy.gif)
![](https://media.giphy.com/media/eBNt5gQ0gHQas/giphy.gif)
