### ISSUE TITLE
Live Coding

### ISSUE THREAD

**Issue by mindovermiles262** [TheOdinProject/discussions#26]
Let's discuss the live coding exercises that we trialed a few weeks ago.

Talking with @leosoaivan in #mod-room and some ideas were thrown around:

* Set a regular schedule - maybe every other week? Once a month?
* Set a plan - Who will be coding? What kinds of challenges?
* See if we can't get a "guest" judge to provide feedback
* Open up Q & A at the end

**Comment by leosoaivan** [comment]
**Frequency**
I think the schedule should focus on the weekend, mainly Friday evenings and Saturday early afternoons. This would allow us to hit the majority of the Americas and European/African population.

In terms of frequency, I would vote for bi-weekly, or tri-weekly.

**Content**
There were a lot of requests for JavaScript.

**Comment by codyloyd** [comment]
I'm for bi-weekly.  We can do some sort of sign-up sheet to schedule them in advance.  IMO up to whoever wants to do one to decide what they're doing.

I'd be down for streaming some JS or CSS.. but it's hard for me to find some alone time outside of the workday so I don't know if I can sign up at the moment.

**Comment by leosoaivan** [comment]
@codyloyd I don't think we necessarily need to discount weekday/workday coding times.

**Comment by codyloyd** [comment]
me either really.. could be good for non-US peeps.

**Comment by leosoaivan** [comment]
What's a good way to create a regular schedule or sign-ups? Is there some free platform out there we could leverage?

**Comment by I3uckwheat** [comment]
@leosoaivan Could we just use google calander?

**Comment by leosoaivan** [comment]
Yeah, do we have a shared one somewhere already?

**Comment by leosoaivan** [comment]
Making a note: Other content could include code-reviews. We can ask for volunteer student solutions in Discord and do a simple, high-level code review.

**Comment by leosoaivan** [comment]
|Date|Type|Streamer|Description and Outcomes|
|-----|-----|---------|-----------------------|
|5/22/20|Review|Leo|Review a student's Tic-Tac-Toe project. Illustrate refactoring opportunities.|

**Comment by ryanford** [comment]
@leosoaivan Do you have a time in mind for this or is it tentative?

**Comment by leosoaivan** [comment]
@ryanford-dev I'll be aiming for 9-ish PM EST.

**Comment by codyloyd** [comment]
this has gotten stale... there's some other discussion floating around, but it's not here so i'm closing this for now.
