### ISSUE TITLE
Move Track decision after webdev101

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/discussions#28]
Many people get confused on what track to follow before they even know what programming is. Maybe we should move the "tracks" decisions to after 101.

This could also open up room for a lesson on which track to pick. Which is a *very* common question we get.

**Comment by codyloyd** [comment]
i thought that was always the plan lol.

Where are they ever presented with that decision anyway?  I think most people just see that there are tracks and take it upon themselves to decide... even though they are put into a default track.

**Comment by I3uckwheat** [comment]
@codyloyd From the homepage, it links directly to the tracks page

**Comment by I3uckwheat** [comment]
https://www.theodinproject.com/
-> "View full curriculum"

**Comment by codyloyd** [comment]
oh yeah

i lost that fight lol.

**Comment by I3uckwheat** [comment]
@codyloyd I think it's time to put the gloves back on.

**Comment by codyloyd** [comment]
Where are we on this?  I know we moved/restructured 101, so I think this issue can be closed, but this is certainly a different topic.
