### ISSUE TITLE
Axe WSL directions from installations

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/discussions#29]
Outdated, unmaintained, unsupported. Why should we keep it?

**Comment by bycdiaz** [comment]
I think we should remove the directions but at least mention that it exists, keeping all the warnings for new learners.

**Comment by leosoaivan** [comment]
I think we should temporarily remove them.

We still want our users to be able to develop in a Unix OS by any means possible. I think WSL2 is viable. From my experiences, it's way easier to set up than a VM or dual-boot.

If we can refine and test-drive the directions to reasonable degree of confidence, I don't think there would be any difference.

**Comment by I3uckwheat** [comment]
@leosoaivan 

I'm less worried about "ease of setup" than I am with continuous understanding. I think we will find people running into a lot of issues with the windows vs Unix filesystems and paths. With how people save things to the desktop on Windows, I feel we are going to breed a lot of developers with very little Unix understanding.

**Comment by mindovermiles262** [comment]
+1 for Axing it

None of the core team really know how to debug (or want to support) WSL

**Comment by ZachBaird** [comment]
+1 for axing. I'm curious how many students opt to try WSL vs. defaulting to Windows and maintainers finding out in Discord they're on Win7 or Win10.

If the content were to be replaced with anything beyond Carlos' recommendation, maybe something like 

> "If you absolutely *must* use Windows for whatever reason, we at least recommend these tools *(insert something like Powershell for the commandline so they at least have aliases for Unix terminal commands)*, but note we cannot provide Windows support... etc etc" 

could be added so that students are at least given some minimal, helpful direction.

**Comment by I3uckwheat** [comment]
I think it's OK for us to be opinionated here, people will still ask in the chat and get frustrated when we can't help. It's not worth the trouble to just tell them to use Linux after they've spent the time to figure things out

**Comment by I3uckwheat** [comment]
https://github.com/TheOdinProject/curriculum/issues/16903

Issue here
