### ISSUE TITLE
19 May 2020 Standup

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/discussions#31]
Follow ups: 
- student submissions
- rails course stuff
- docs/onboarding for maintainers.  new maintainers?
- live coding schedule/organization
- proposal approval process (issue with voting comment)
- moving track choice

New Stuff:
- Working-group meetings/formation (HTML/CSS course) https://github.com/TheOdinProject/discussions/issues/32

**Comment by I3uckwheat** [comment]
docs/onboarding:
 Documentation completed for maintainers, wording intentionally left vague, special thanks to Infamous and Carlos.

**Comment by KevinMulhern** [comment]
Student Submissions:
* Bit of progress with reporting. 

Goals for next week:
* Have frontend components done
* Move reporting along a bit by triggered message to discord

**Comment by leosoaivan** [comment]
Live-coding:
- Basic markdown format, but need a dedicated doc?
