### ISSUE TITLE
Working Groups

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/discussions#32]
HTML/CSS course needs a hefty rework.... but there are some decisions that need to be made about what content is included, the scope and sequence of the material and when/where it lies in the curriculum.

I think we need to form some sort of small committee or working-group that can hash out some of these details before we create an official proposal.

Not sure if we need an official process for this or if I should just ask for volunteers and start a new discussion issue, discord-channel or whatever.   Not sure if there is an optimal number of collaborators here either.

discuss. 😃

**Comment by ryanford** [comment]
I'm in. I'm not sure if we can *reliably* do both but that would be nice. Channels are nice for preliminary discussions, but serious proposals / ideas for consideration would be better in a GH issue imo.

**Comment by codyloyd** [comment]
yeah I agree.. a discord channel seems a better place for actually hashing stuff out... but it kind of depends on who and how many people get in there and start throwing ideas around.

**Comment by mindovermiles262** [comment]
> I think we need to form some sort of small committee or working-group that can hash out some of these details before we create an official proposal.

Like... project owners?

**Comment by ryanford** [comment]
We can possibly give the champion [team] speaking privileges in the channel and give the rest of the working group read/react privileges. Keep the discussion light/on-topic but still allow us to delegate/offer assignments. Rest of the working group could still vote/express interest via reacts.

**Edit**: I wonder if it would just be easier to keep the teams small and kick unruly members though :thinking:
