### ISSUE TITLE
Maintainers onboarding/guidlines

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/discussions#33]
# Maintainers

### Maintain Issues

- A maintainer should spend time maintaining the Github
- As a maintainer, you should use your discretion on which issues *you* should take yourself. Part of your goal, is to increase contrubutions from the entire community
- **Delete/Close** irrelevant and unhelpful issues and comments
    - **Explain reasoning for closing issue**
    - Before deletion, ask for more info if issue could be viable 
    - People asking for help on projects, should be directed to the forum or chat before deletion
- **Add tags to issues as applicable** (Check the right side of the page on an open issue)
    - e.g. "First Time Only" (for super easy issues, to help gain more contributors)
- **Modify issue contents with more information that could be relevant**
    - Adding a checklist for definition of "success" for whoever takes the issue
    - Suggestions on possible solutions
- **Ask for contributions in the #contributions-opportunities channel**
    - Do not go overboard, people don't like getting pinged a lot
    - Consider batching requests in one ping
- **Assign issues to those claiming it** (Check the right side of the page on an open issue)
    - People should comment on the issue they are working on the issue
- **Moving issues to the proper section on the project board** (Check the right side of the page on an open issue)
    - Curriculum issues should be attached to the 'curriculum' project board
    - Most things will be "backlog" unless it breaks significant parts of the course
        - e.g. Hartl puts his books behind a paywall
    - When assigned to somebody, issue should be put in "in-progress"
        - Don't be afraid to check up on people working on issues
    - Issues with attached PRs will be closed automatically
- **Keep an eye on the project board**
    - Feel free to follow up with people, but give them ample time

### Maintain PRs (Pull Requests)

- **Close PRs** that are irrelevant, or clearly unhelpful to the project
    - e.g. Somebody PRs solutions to any lesson that is to be cloned and filled out
        - https://github.com/TheOdinProject/javascript-exercises
    - Be sure to give a reason for closing the PR
- **Attach issues** to the PR that should be closed when the PR is merged (Check the right side of the page on an open PR)
- **Review thoroughly**
    - Look very closely at the markdown
    - Utilize the request changes feature when reviewing code/lesson content
        - Feel free to fix small typos and wording using the in-browser editor
        -  https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews
    - New lessons will have to have the "seeds" file updated to accomodate and show on the site
- **Updates** to the markdown will be reflected on the site **once a day**
    - If somebody asks why their PR isn't showing, this is why
- **Merge PRs**
    - Since you are a maintainer, we trust your judgement. With git, everything can be reverted, so don't be afraid to merge things
        - Ask Kevin about his screw-ups (and Marvin)
    - If a PR looks to be good, feel free to merge after review
    - Do not merge if you are unsure, ask somebody else for review

### Maintain, follow, and enforce rules

- As a maintainer, you will be expected to **adhere to** and **uphold** the rules as detailed and maintained in the `#rules` channel in the Discord at all times. 
- **Kick users from the discord**
    - Primarily, due to the inability to adhere to the rules
    - Users within the community, should be warned first
    - Exercise 'common sense' discretion when doing so
    - Rules are meant to be relaxed
    - Kick clear phishers and spammers immediately
- **Modify the `loki?` role for new members and rule-breakers** (see: `#i-didnt-read-the-rules`)
    - Usually adding the `loki?` role to somebody not paying attention, is enough
    - Abuse of the bot should result in the assignment of the `NOBOT` role
- **`Delete` messages from all channels.**
    - Use discretion
    - Screenshots before deletion
    - Immediately delete content that breaks rules about etiquette (within reason)
    - Malicious messages should be deleted
        - e.g. If somebody is attempting to get somebody to run `rm -rf /`
        - Somebody is looking for help with "phishing" or other illegal activities
- **`Change Nickname` permissions.**
    - User nicknames _should_ adhere to our rules
    - Abuse of this permission will not be tolerated
    
### Keep an eye on #i-didnt-read-the-rules 
- Watch and remove the `loki?` role to those that have read the rules and clicked "OK"
    - You can see if they have clicked "OK" by looking for their name in the reaction list in #rules

**Comment by I3uckwheat** [comment]
@bycdiaz @marvingay and I have gone over what a maintainer should know how to do and have guidelines about. 

I am unsure where to store this to make it official. Please request changes if needed.

**Comment by codyloyd** [comment]
> I am unsure where to store this to make it official.

i think a markdown file living in 'discussions' is appropriate.  we can just send it to candidates when we invite them to be a maintainer.

Haven't read contents yet

**Comment by I3uckwheat** [comment]
@codyloyd After a few more comments, i'll make a PR for it

**Comment by I3uckwheat** [comment]
https://github.com/TheOdinProject/discussions/pull/34

PR here
