### ISSUE TITLE
Discussion: Making WD101 it's own track.

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/discussions#39]
The problem we're trying to solve here: People not knowing which track to choose, or trying to select their track too early.

One of the most significant issues we've had since creating our 'tracks' system is that it gives students a bit of a burden of choice upfront.  It would be nice if we could altogether remove that choice until after students have completed WD101.

My idea is that breaking 101 into a completely separate track and sticking _every_ student in that track upfront will remove that choice or at least defer it.  It will give everyone a much more definite "START HERE" signpost.

Potential downsides:
 - people will just skip it and go straight to whatever track they think they want to do
 - By itself, 101 will not make anyone job-ready, so that makes it a little different from any of our current tracks.

There may be downsides I haven't thought of though.. so let's discuss!

**Comment by I3uckwheat** [comment]
I think up-front we should let them know what the options are, and that they shouldn't worry about choosing one.

Then at the end of 101, give them way more information on how to choose, what the advantages of each are, and as @bycdiaz said, really drill in the fact that learning to be a programmer is more important and both tracks will take you there.



---


This may also be a good time to re-consider what "101" really is and what webdev 101 should actually contain.

**Comment by Ikass** [comment]
How about a bit more results-oriented approach, i.e., "at the end of the WD101 Course you will be able to build from scratch simple, elegant, functional, standards based, responsive, accessible static websites, using git version control, host them on GitHub. You will be comfortable making single-page marketing or landing pages for your own projects or for clients."

For example, I just went through a short Le Wagon web-dev [online course](http://honoris.net/learntocode/) (approx. 20 hours to complete) - at the very beginning they showed examples of the two projects [I would build](https://ikass.github.io/my-profile-lewagon/) and it got me excited (a portfolio and a landing page). The course itself was video, text and hands-on projects.

**Comment by codyloyd** [comment]
hey look we did this.
