### ISSUE TITLE
Ideas that belong to more than one track

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/discussions#4]
My understanding is that we are currently considering whether each track could work in isolation. I know it's been mentioned one of the great things about Odin is that each course builds upon the last but I know it's also been muted that we could have a complete course, a frontend and a backend one that work independently of each other. Having course work on a standalone basis may also attract more people who have perhaps completed a backend course in something like node but just want to work on their frontend knowledge or vice versa.

While looking at the Ruby course I've noted that it covers many of the things that equally applies to something like the JS course (computer science and possibly in the future common design patterns). The JS course sits across both the frontend and the backend so it's plausible that people could take the JS course without looking at the Ruby one and miss out on some pretty important topics.

What are peoples thoughts on this?

Does it make sense for each track to cover these topics as relevant to the languages or is there scope to make these more language agnostic and let students work on them in the language of their choice (Ruby or JS). Computer science and design patterns are common across all languages after all.

Having it as a separate track is an issue because it would be best placed before you finish the end of the Ruby or JS track and if you tried to have something you just plugged into the relevant parts you would end up with duplication for those students who do the Ruby course then the JS one so maybe it would be better to have those lessons focused on that particular language's implementation.

**Comment by codyloyd** [comment]
I have also been wondering how this should work.  I think the best option for the moment might be to just recycle and rewrite content for each language, because while CS ideas and patterns etc. ARE common across languages, they way they are implemented can vary wildly... and I think those lessons need to have code examples within them. 

In any case, it shouldn't be too hard to just copy/paste the explanations and content and rewrite the code snippets or edit the lesson when appropriate.

**Comment by KevinMulhern** [comment]
This is a great point @CouchofTomato, I reckon theres scope for a language agnostic computer science course.
