### ISSUE TITLE
A Few Questions

### ISSUE THREAD

**Issue by ECI03** [TheOdinProject/discussions#46]
I don't know if this is the right place to ask questions but here it goes anyway.  I am planning on starting TOP very soon. I have a few questions about the program.  If I plan on freelancing, what path should I take? If it does not matter, which path takes the least amount of time? Also, if I wanted to complete the course in 6 months, how many hours would I have to do a day? What about ten months? A year? If this is the wrong place to ask these types of questions, would someone please direct me to the correct place?

**Comment by twalton83** [comment]
Please ask all questions in our Discord channel (navigate to our website, a link is in the bottom right corner).

Also, as a heads up, there is no way to judge how long it will take, neither path inherently takes less time. When you enter our Discord server you can read our FAQ which covers this question.
