### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/discussions#5]
Someone in the gitter chat raised a query about whether the Odin site itself could have a dark theme as it's a bit bright for reading.

Just putting it here as an issue for future consideration.

**Comment by KevinMulhern** [comment]
@adachiu whats your thoughts on this? is it doable?

**Comment by CouchofTomato** [comment]
The alternative is we can create a page highlighting many of the browser plugins that offer that functionality. 

It would probably also be a quick fix even if we did want to develop the theme in house

**Comment by KevinMulhern** [comment]
I'm not that familiar with page highlighting @CouchofTomato do you know of any example sites we could take a look at it? 😄

**Comment by mindovermiles262** [comment]
IMO if a user wants a dark theme (s)he can install a text-reader or some other plugin as @CouchofTomato has suggested
