### ISSUE TITLE
Single Sources of Truth

### ISSUE THREAD

**Issue by mindovermiles262** [TheOdinProject/discussions#6]
We should all determine the single sources of truth for various components of TOP.

For example - we have 2 or 3 project boards. Which one is accurate?

Wikis, Projects, etc can be disabled on GH if we don't use them.

A few components that I can think of off the top of my head:

- [ ] Project Boards (Direction of TOP)
        VOTE: Trello
- [ ] Wiki
- [ ] Code of conduct
- [ ] Licensing
- [ ] Contributing Guide

Please add any other components you think would benefit from SST

**Comment by KevinMulhern** [comment]
Hey @mindovermiles262, great question to have some discussion around.

The project boards have been duplicated quite a bit, I vote Trello as the source of truth with that one.

As for the other ones, are there any duplicates of them? or do you think we could maybe consolidate some?
