### ISSUE TITLE
Project 404s

### ISSUE THREAD

**Issue by mindovermiles262** [TheOdinProject/discussions#7]
I think I've found a way for us to search the projects and check for any 404s that are returned.

That being said - how should we deal with these?  I don't think it's great for TOP to be hanging on to them but these people have taken the effort to submit their projects.

Any ideas of how to proceed would be great

**Comment by KevinMulhern** [comment]
IMO removing them would be the best approach, the only other way I can see with dealing with this would be contacting the students about it. But that would be intrusive and too labour intensive.

**Comment by mindovermiles262** [comment]
Which leads to another question - Do we leave up the links the codebase? I.e. `Kevin's Solution - View in Browser` would turn into just `Kevin's Solution`

**Comment by KevinMulhern** [comment]
Good question, I'd personally vote to leave the link to github for them.
