### ISSUE TITLE
21 April Standup

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/discussions#8]
Comment here with things you think we ought to hash out in our first standup.

If you missed the discord discussion.. we all have a lot of great ideas, but we don't have any process for properly discussing, planning and implementing them.  To facilitate that we've set up a weekly standup on Tuesday at 1300UTC.  If you are a TOP moderator, to be added to this meeting DM Andy on discord. (sorry any non-mods seeing this note)

IMO priority #1 needs to be getting a process lined out for how we organize and implement the various initiatives we have.

Tentative Meeting Agenda

- [x] project planning process
  - how and when do real decisions get made (needs to be async).
    - we can chat in discord of course.. but we need something more persistent and more accessible to those from different timezones for real discussion and decision making.
  - what should a project plan include
  - when is a project plan "approved" or ready?  How many people need to sign off on it?
  - how do we decide which projects are pursued... what does it take to veto a project entirely?
  - details for how projects are actually run.. creating issues, divvying up the work etc.
- [x] reorganizing team roles
  - retiring inactive mods/purps
  - add new role for 'maintainers'
  - define the specifics and/or requirements of each role
  - declare myself dictator and kick everyone else off team
- [x] specific projects
  - curriculum improvements
  - seeds file rework
  - gamification
  - analytics: student feedback, student completion data etc.
- [x] student submissions
  - current solution buries any real work on the curriculum.

**Comment by I3uckwheat** [comment]
Could be nice to discuss student submissions

**Comment by I3uckwheat** [comment]
Would also be nice to know if we can make this re-occurring

**Comment by codyloyd** [comment]
@I3uckwheat it already is

**Comment by I3uckwheat** [comment]
Examples of why we need a submission process that isn't git

https://github.com/TheOdinProject/learn_ruby/pull/68
https://github.com/TheOdinProject/learn_ruby/pull/66
https://github.com/TheOdinProject/learn_ruby/pull/64
