### ISSUE TITLE
28 April Standup

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/discussions#9]
Previous Standup: #8 | [notes](https://github.com/TheOdinProject/discussions/blob/master/meeting-notes/2020-04-21-standup.pdf)

Agenda:
- [x] Previous items progress
  - Odin Project Planning: Andy
  - Student Project Submissions: Kevin
  - Team reorganization: Briggs #22 
  - Curriculum Improvements: Andy
- [x] botstuff
  - hooks for github/forum etc. #10 
  - admin stuff (dashboard or through discord.. maybe both?) #12 
- [x] dashboard re-design TheOdinProject/theodinproject#1116

**Comment by mindovermiles262** [comment]
We should record notes in something other than .pdf as links cannot be followed.

**Comment by ryanford** [comment]
See #12 for bot stuff and #10 for hooks discussion

**Comment by I3uckwheat** [comment]
> We should record notes in something other than .pdf as links cannot be followed.

We should also video record these meetings.

**Comment by mindovermiles262** [comment]
~~Bringing up https://github.com/TheOdinProject/discussions/issues/13~~

~~Discuss adding a temporary student submission form to reduce amount of daily PR approvals.~~

**Comment by mindovermiles262** [comment]
@adachiu dashboard redesign https://github.com/TheOdinProject/theodinproject/issues/1116
